### ISSUE TITLE
Parallel branches

### ISSUE THREAD

**Issue by stacygrace** [trek10inc/sfn-yaml-macro#2]
This is pretty great so far but I got stuck on how to write the Branches field of my Parallel task. How does that need to look in order to compile?

**Comment by stacygrace** [comment]
Neeeeever mind, the problem was a totally different and unrelated syntax error that was at fault. Works great!

**Comment by stacygrace** [comment]
Well, I've come back to this issue for real this time. 

I don't think the script is capturing the nested states inside a Parallel block. Here's a screenshot of what the output of the script looked like. I'm not sure if the resource part of that first Task in the screenshot got translated right either but that's a different issue.

Note the States block in the Branches section and it doesn't seem that the script is pulling in those resources to transform them.



![parallel](https://user-images.githubusercontent.com/15710088/70582465-7b2ba880-1b6f-11ea-84e8-1295319eae60.jpg)

**Comment by mbarneyjr** [comment]
After doing some digging it seems the macro is not handling arrays properly, we'll take a look, thanks for the bug report!

**Comment by mbarneyjr** [comment]
Hi @chadmorrow, this should be fixed in version 0.2.2

Please feel free to re-open if you're still experiencing issues! Thanks for trying this out!

**Comment by aidansteele** [comment]
@mbarneyjr Sorry to be a pain, but I'm using 0.2.2 and seem to have the same issue with the following template:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: [SFNYAML, AWS::Serverless-2016-10-31]
Resources:
  StepRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: !Sub states.${AWS::Region}.amazonaws.com
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: "*" # lets see if we can tone this down. name prefix? tags?
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepRole.Arn
      DefinitionString: # thanks to the SFNYAML transform
        StartAt: Collect account ids
        States:
          Collect account ids:
            Type: Task
            Resource: !GetAtt CollectorFunction.Arn
            Next: For each account
          For each account:
            Type: Map
            ItemsPath: $.AccountIds
            Iterator:
              StartAt: Hello
              States:
                Hello:
                  Type: Task
                  Resource: !GetAtt HelloFunction.Arn
                  End: true
            End: true
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: step-everywhere
      CodeUri: ./step-everywhere
      MemorySize: 128
      Timeout: 30
      AutoPublishAlias: live
      Environment:
        Variables:
          Mode: Hello
  CollectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: step-everywhere
      CodeUri: ./step-everywhere
      MemorySize: 128
      Timeout: 30
      AutoPublishAlias: live
      Environment:
        Variables:
          Mode: Collector

```
