### ISSUE TITLE
YML interpretation of !Sub causes errors when a definition has quotes

### ISSUE THREAD

**Issue by ryansb** [trek10inc/sfn-yaml-macro#4]
Example: 
```
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${AWS::StackName}-StateMachine'
      DefinitionString:
        StartAt: FindKeysQuery
        States:
          FindKeysQuery:
            Type: Pass
            Next: Success
            ResultPath: $.query
            Result: !Sub |
              SELECT DISTINCT "$path"
              FROM "${LogsDatabase}"."${SourceTable}"
              WHERE from_unixtime(timestamp/1000) < (date_trunc('day', now()) - interval '1' hour)
              ORDER BY "$path"
          Success:
            Type: Succeed
```

In this example state machine, I get a whole raft of errors about bad quotes/control chars

```
Invalid State Machine Definition: 'INVALID_JSON_DESCRIPTION: Unexpected character ('$' (code 36)): was expecting comma to separate Object entries at [Source: (String)"{ "States": { "DeleteOldKeys": { "Type": "Task", "Retry": [ { "ErrorEquals": [ "States.ALL" ], "MaxAttempts": 1, "IntervalSeconds": 60 } ], "Resource": "arn:aws:lambda:us-west-2:454679818906:function:rsb-waf-partitioner-DeleteOldS3Objects-1G1JXDL4NK13B", "Next": "Success" }, "FindKeysQuery": { "Type": "Pass", "ResultPath": "$.query", "Result": "SELECT DISTINCT "$path""[truncated 1539 chars]; line: 20, column: 36] at [Source: (String)"{ "States": { "DeleteOldKeys": { "Type": "Task", "Retry": [ { "ErrorEquals": [ "States.ALL" ], "MaxAttempts": 1, "IntervalSeconds": 60 } ], "Resource": "arn:aws:lambda:us-west-2:454679818906
```

Adding a `\` or `\\` just adds new control character errors.
